/**
 * @file                        :layout.tsx
 * @description                 :Root Layout component for the Next.js Application
 * @author                      :Jobet P. Casquejo
 * @last_modified_on            :12-23-20254
 * @last_modified_by            :Jobet P. Casquejo
 *
 * ===========================================================================================
 * Modifications Log
 * Ver                    Date                    Author                  Modification
 * 1.0                    12-23-20254             Jobet P. Casquejo       Initial Version
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Google font Geist Sans.
 * @type {ReturnType<typeof Geist>}
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Google font Geist Mono.
 * @type {ReturnType<typeof Geist_Mono>}
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata for the Next.js application.
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component for the application.
 *
 * Provides the HTML structure, including Google fonts and antialiased body.
 *
 * @param {Object} props - Component props.
 * @param {React.ReactNode} props.children - The page content to render inside the layout.
 * @returns {React.ReactElement} The layout component wrapping children with HTML and body tags.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
